[project]
name = "cfpb-complaint-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kekgerman", email = "kekgerman81@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
cfpb-complaint-classifier = "cfpb_complaint_classifier:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
